project:
  type: website

website:
  title: "Salman Bin Habib"
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - text: "Assignments"
        menu:
          - text: "Assignment 2"
            href: Assignments/Assignment_2.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



